# Generated by Django 4.2.4 on 2023-08-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('Match_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('Season', models.CharField(blank=True, max_length=4, null=True)),
                ('Split', models.CharField(blank=True, max_length=20, null=True)),
                ('Week', models.CharField(blank=True, max_length=20, null=True)),
                ('Blue', models.CharField(blank=True, max_length=5, null=True)),
                ('Red', models.CharField(blank=True, max_length=5, null=True)),
                ('WinnerT', models.CharField(blank=True, max_length=5, null=True)),
                ('Patch', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(blank=True, max_length=4, null=True)),
                ('Split', models.CharField(blank=True, max_length=20, null=True)),
                ('Team', models.CharField(blank=True, max_length=50, null=True)),
                ('Player', models.CharField(blank=True, max_length=50, null=True)),
                ('Side', models.CharField(blank=True, max_length=50, null=True)),
                ('Games', models.CharField(blank=True, max_length=50, null=True)),
                ('Champion', models.CharField(blank=True, max_length=50, null=True)),
                ('CKey', models.CharField(blank=True, max_length=50, null=True)),
                ('Win', models.IntegerField(blank=True, null=True)),
                ('Lose', models.IntegerField(blank=True, null=True)),
                ('Kills', models.IntegerField(blank=True, null=True)),
                ('Deaths', models.IntegerField(blank=True, null=True)),
                ('Assists', models.IntegerField(blank=True, null=True)),
                ('KillsC', models.IntegerField(blank=True, null=True)),
                ('DeathsC', models.IntegerField(blank=True, null=True)),
                ('AssistsC', models.IntegerField(blank=True, null=True)),
                ('KDA', models.FloatField(blank=True, null=True)),
                ('KDA_C', models.FloatField(blank=True, null=True)),
                ('Bans', models.IntegerField(blank=True, null=True)),
                ('Avg_BT', models.FloatField(blank=True, null=True)),
                ('WR', models.FloatField(blank=True, null=True)),
                ('Presence', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(blank=True, max_length=4, null=True)),
                ('Split', models.CharField(blank=True, max_length=20, null=True)),
                ('Week', models.CharField(blank=True, max_length=20, null=True)),
                ('Type', models.CharField(blank=True, max_length=10, null=True)),
                ('Team', models.CharField(blank=True, max_length=5, null=True)),
                ('Player', models.CharField(blank=True, max_length=50, null=True)),
                ('X', models.IntegerField(blank=True, null=True)),
                ('Y', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PicksBans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BB1', models.CharField(blank=True, max_length=50, null=True)),
                ('BB2', models.CharField(blank=True, max_length=50, null=True)),
                ('BB3', models.CharField(blank=True, max_length=50, null=True)),
                ('BB4', models.CharField(blank=True, max_length=50, null=True)),
                ('BB5', models.CharField(blank=True, max_length=50, null=True)),
                ('RB1', models.CharField(blank=True, max_length=50, null=True)),
                ('RB2', models.CharField(blank=True, max_length=50, null=True)),
                ('RB3', models.CharField(blank=True, max_length=50, null=True)),
                ('RB4', models.CharField(blank=True, max_length=50, null=True)),
                ('RB5', models.CharField(blank=True, max_length=50, null=True)),
                ('BPPlayer1', models.CharField(blank=True, max_length=50, null=True)),
                ('BP1', models.CharField(blank=True, max_length=50, null=True)),
                ('BPPlayer2', models.CharField(blank=True, max_length=50, null=True)),
                ('BP2', models.CharField(blank=True, max_length=50, null=True)),
                ('BPPlayer3', models.CharField(blank=True, max_length=50, null=True)),
                ('BP3', models.CharField(blank=True, max_length=50, null=True)),
                ('BPPlayer4', models.CharField(blank=True, max_length=50, null=True)),
                ('BP4', models.CharField(blank=True, max_length=50, null=True)),
                ('BPPlayer5', models.CharField(blank=True, max_length=50, null=True)),
                ('BP5', models.CharField(blank=True, max_length=50, null=True)),
                ('RPPlayer1', models.CharField(blank=True, max_length=50, null=True)),
                ('RP1', models.CharField(blank=True, max_length=50, null=True)),
                ('RPPlayer2', models.CharField(blank=True, max_length=50, null=True)),
                ('RP2', models.CharField(blank=True, max_length=50, null=True)),
                ('RPPlayer3', models.CharField(blank=True, max_length=50, null=True)),
                ('RP3', models.CharField(blank=True, max_length=50, null=True)),
                ('RPPlayer4', models.CharField(blank=True, max_length=50, null=True)),
                ('RP4', models.CharField(blank=True, max_length=50, null=True)),
                ('RPPlayer5', models.CharField(blank=True, max_length=50, null=True)),
                ('RP5', models.CharField(blank=True, max_length=50, null=True)),
                ('Match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOLStatium_app.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(blank=True, max_length=5, null=True)),
                ('Player', models.CharField(blank=True, max_length=10, null=True)),
                ('Champion', models.CharField(blank=True, max_length=10, null=True)),
                ('KDA', models.FloatField(blank=True, null=True)),
                ('Gold', models.IntegerField(blank=True, null=True)),
                ('TJK', models.IntegerField(blank=True, null=True)),
                ('EJK', models.IntegerField(blank=True, null=True)),
                ('JS', models.IntegerField(blank=True, null=True)),
                ('Match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LOLStatium_app.match')),
            ],
        ),
    ]
