# Generated by Django 4.2.4 on 2023-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOLStatium_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistory',
            name='Champion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matchhistory',
            name='Player',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
